apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-learning
  labels:
    app: devops-learning
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-learning
  template:
    metadata:
      labels:
        app: devops-learning
    spec:
      containers:
      - name: devops-learning
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 8888
