apiVersion: v1
kind: Service
metadata:
  name: devops-learning-service
spec:
  type: NodePort
  selector:
    app: devops-learning
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 30008
